apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-backend
  template:
    metadata:
      labels:
        app: game-backend
    spec:
      containers:
      - name: game-backend
        image: 590183739327.dkr.ecr.ap-south-1.amazonaws.com/game-backend:14
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: game-backend
spec:
  selector:
    app: game-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
