resources:
  - deployment.yaml
images:
  - name: 590183739327.dkr.ecr.ap-south-1.amazonaws.com/game-backend
    newTag: b635b41e4c61633b462a5c6314d614c02cc00380 # CI will overwrite this to the git SHA
