apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-frontend
  template:
    metadata:
      labels:
        app: game-frontend
    spec:
      containers:
      - name: game-frontend
        image: 590183739327.dkr.ecr.ap-south-1a.amazonaws.com/game-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: game-frontend
spec:
  type: LoadBalancer
  selector:
    app: game-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
